### ISSUE TITLE
Links in the main readme.md are broken

### ISSUE THREAD

**Issue by rustyjux** [bcgov/inclusive-names-service#6]
the links to all directories in the repo are broken

Link: https://github.com/bcgov/inclusive-names-service/blob/main/.%5Cprogramming_languages%5CREADME.md
shouldl be: https://github.com/bcgov/inclusive-names-service/tree/main/programming_languages
or perhaps https://github.com/bcgov/inclusive-names-service/blob/main/programming_languages/README.md

**Comment by mdunhamwilkie** [comment]
Thanks @rustyjux . I believe I've corrected these now.
